Requests logging
trafi/maas-components pull request #35
Opened 2020-12-08 09:50 UTC by TomasSkar

Added requests logging for android.

Dependencies: https://ktor.io/docs/features-logging.html
Also for Android, we need add **SLF4J** logging provider, more details: https://ktor.io/docs/servers-logging.html

For now, leaving iOs dependency commented

![image](https://user-images.githubusercontent.com/55691605/101467363-e22e9980-394a-11eb-99d3-8f28ed2be1c4.png)

2020-12-08 12:03 UTC, justasm requested changes
Really happy to see this initiative, this is one thing we need to solve 👍 We need to make this configurable in some way such that
1. the SDK does not log anything (except for incorrect API usage) by default
1. logging can be enabled / disabled by the SDK user
1. ~logging can be customized by the SDK user (nice-to-have)

2020-12-08 12:03 UTC, justasm commented on common/core/src/commonMain/kotlin/com/trafi/core/HttpClient.kt
> +        level = LogLevel.ALL
We need a way to avoid enabling logging of everything for all SDK users.

2021-02-01 07:27 UTC, justasm commented on common/core/src/commonMain/kotlin/com/trafi/core/ApiConfiguration.kt
> +    val logger: Logger? = null,
This is the key API change.

2021-02-01 19:59 UTC, justasm reviewed
Tested with the Android sample app, working as expected 👍

2021-02-04 08:14 UTC, justasm approved these changes

2021-02-04 11:36 UTC, Ignelios approved these changes
LGTM

2021-02-04 11:40 UTC, merged